name: lesbrary
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=0.24.0=py37_0
  - blas=1.0=mkl
  - bokeh=1.3.4=py37_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.5.15=1
  - cartopy=0.17.0=py37hbb7e04d_1
  - certifi=2019.6.16=py37_1
  - cffi=1.12.3=py37h2e261b9_0
  - cftime=1.0.3.4=py37hdd07704_1001
  - chardet=3.0.4=py37_1003
  - click=7.0=py37_0
  - cloudpickle=1.2.2=py_0
  - cryptography=2.7=py37h1ba5d50_0
  - curl=7.65.3=hbc83047_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.0=py37h7b6447c_0
  - dask=2.3.0=py_0
  - dask-core=2.3.0=py_0
  - dbus=1.13.6=h746ee38_0
  - distributed=2.3.2=py_1
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fsspec=0.4.0=py_0
  - geos=3.7.1=he6710b0_0
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.0=py37_2
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_0
  - intel-openmp=2019.4=243
  - jinja2=2.10.1=py37_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py37he6710b0_0
  - krb5=1.16.1=h173b8e3_7
  - libcurl=7.65.3=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libnetcdf=4.6.1=h11d0813_2
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.8.2=h1ba5d50_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - libxslt=1.1.33=h7d1a2b0_0
  - locket=0.2.0=py37_1
  - lxml=4.4.1=py37hefd8a0e_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.1=py37h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - msgpack-python=0.6.1=py37hfd86e86_1
  - ncurses=6.1=he6710b0_1
  - netcdf4=1.4.2=py37h808af73_0
  - numpy=1.16.5=py37h7e9f1db_0
  - numpy-base=1.16.5=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1d=h7b6447c_1
  - owslib=0.18.0=py_0
  - packaging=19.1=py37_0
  - pandas=0.25.1=py37he6710b0_0
  - partd=1.0.0=py_0
  - pcre=8.43=he6710b0_0
  - pillow=6.1.0=py37h34e0f95_0
  - pip=19.2.2=py37_0
  - proj4=5.2.0=he6710b0_1
  - psutil=5.6.3=py37h7b6447c_0
  - pycparser=2.19=py37_0
  - pyepsg=0.4.0=py37_0
  - pykdtree=1.3.1=py37hdd07704_2
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyproj=1.9.6=py37h14380d9_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyshp=2.1.0=py_0
  - pysocks=1.7.0=py37_0
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.2=py_0
  - pyyaml=5.1.2=py37h7b6447c_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_0
  - scipy=1.3.1=py37h7c811a0_0
  - setuptools=41.0.1=py37_0
  - shapely=1.6.4=py37h86c5351_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sortedcontainers=2.1.0=py37_0
  - sqlite=3.29.0=h7b6447c_0
  - tblib=1.4.0=py_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h7b6447c_0
  - urllib3=1.24.2=py37_0
  - wheel=0.33.4=py37_0
  - xarray=0.12.1=py_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zict=1.0.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
prefix: /home/alir/miniconda3/envs/seasonal_cycle

